- scripts/tract_math
- tract_querier/tract_math/decorator.py
- tract_querier/tract_math/operations.py
This patch provide possibility to add optional
flags to tract_math.
Optional flags are always start with "--" and
are considered as boolean flags.
This patch shold be backwards compatible, and previous results
should be created if not options are specified.
A newly added optional flag is "--useFileNamesAsIndex".
When this flag is used, the created csv output table uses
tractography file names instead of index IDs.
The --useFileNamesAsIndex col_name1:path_dir_index col_name2:path_dir_index2 .. col_nameN:path_dir_indexN
Example directory layout:
=========================
PROJ_XX/SUBJ_01/SESSION_AB/cm1.left.vtp
PROJ_XX/SUBJ_01/SESSION_AB/cm1.right.vtp
||||||| ||||||| |||||||||| ||||||||||||||||||||||||
4444444 3333333 2222222222 111111111111111111111111
tract_math call:
================ …
> ENH: Added option to improve creating csv files

- tract_querier/tract_math/tensor_operations.py
OK   md_by_point[index] = scalar_measures.mean_diffusivity(eigenvals)
OK   ax_by_point[index] = scalar_measures.axial_diffusivity(eigenvals)
BUG  rd_by_point[index] = scalar_measures.axial_diffusivity(eigenvals)
^^^^^^^^^^^^^^^^^
OK   ga_by_point[index] = scalar_measures.geodesic_anisotropy(eigenvals)
Clearly this is a bug.  All the AX measures are correct, all the RD
measures are wrong for these results.
resolves: #27
> BUG: RD incorrectly computed with axial_diffusivity

- scripts/tract_math
The flag --useFileNamesAsIndex was changed in the code to
--use_file_names_as_index.  This will require all scripts
that use this feature to be rewritten.  It is currently
silently doing the wrong behavior rather than producing a
meaningful failure message.
> DOC: Incorrect documentation for use_file_names_as_index

- tract_querier/__init__.py
When installing tract_querier in non-system folders, e.g. with `python setup.py install --user`, tract_querier is unable to find the queries and triggers `Exception: Default path for queries not found` and immediately stop working. The issue is in `find_queries_path()`, where `sysconfig.get_path()` uses only the default scheme, see: [https://docs.python.org/3/library/sysconfig.html#installation-paths](url). This patch fixes the issue by looping through all schemes supported by Python. See issue #39.
> FIX: find_queries_path() now explores all sysconfig schemes

- README.md
Add GHA build status badge to `README` and remove the TravisCI build link as it is no longer active.
> ENH: Add GHA build status badge to `README`

- pyproject.toml
Transition to more modern versions of dependencies:
- Require `NumPy` equal or greater than 1.23.0.
- Require `NiBabel` equal or greater than 3.0.0.
`NiBabel` 3.0.0 still has the `trackvis` module support, and the minimum previous version of `NumPy` (1.21.0) did not work locally, deadlocking in the tractography testing suite.
> ENH: Transition to more modern versions of dependencies

- .github/workflows/doc_build.yaml
- doc/conf.py
- ENH: Add documentation build GHA workflow file
- BUG: Make the documentation config file `latex_preamble` be a literal
- BUG: Provide a class name to the `Sphinx` lexer
> ENH: Add documentation build GHA workflow file

- .github/workflows/test_package.yaml
- pyproject.toml
- tract_querier/tests/test_query_eval.py
- tract_querier/tests/test_query_files.py
- tract_querier/tests/test_query_rewrite.py
- tract_querier/tests/test_scripts.py
- tract_querier/tractography/tests/test_tractography.py
Use `pytest` for testing instead of `nose`: `nose` is no longer maintained and its successor maintainers `nose2` encourage to use `pytest` as it as a bigger team of maintainers and a larger community of users.
Avoids errors that stem from using `nose` as the testing tool:
```
AttributeError: module 'collections' has no attribute 'Callable'
```
raised for example in:
https://github.com/demianw/tract_querier/actions/runs/12168541455/job/33939552914#step:6:37
Documentation:
https://github.com/nose-devs/nose2
https://docs.pytest.org/en/latest/
> ENH: Use `pytest` for testing instead of `nose`

- pyproject.toml
- tract_querier/tract_label_indices.py
- tract_querier/tract_math/decorator.py
- tract_querier/tract_math/operations.py
- tract_querier/tractography/trackvis.py
- tract_querier/tractography/tractography.py
- tract_querier/tractography/vtkInterface.py
Do not import `range` from `six`: `six` is a Python 2 and 3 compatibility library. Since support for Python 2 was dropped following the discussion in https://github.com/demianw/tract_querier/pull/53, this patch set removes `six` as a dependency of the project.
The built-in Python `range()` is equivalent to the `six.moves.range` method, so adopt the former by avoiding to import it from `six.moves`.
Similarly, use `range()` instead of `xrange()`, which is only supported in Python 2. Both are equivalent.
Documentation:
https://pypi.org/project/six/
> ENH: Do not import `range` from `six`

- tract_querier/tensor/tests/test_scalar_measures.py
- tract_querier/tests/test_query_eval.py
- tract_querier/tract_math/tract_obb.py
- tract_querier/tractography/tests/test_tractography.py
Use `NumPy` random generators as they are the preferred way to create random numbers since version 1.17.0.
Fix the seeds for the cases were they were not being fixed for the sake of reproducibility, except for `test_query_eval.py` where fixing the seed may make the `while` loop be infinite.
Documentation:
https://numpy.org/doc/1.17/reference/random/index.html
> ENH: Use `NumPy` random generators

- .github/workflows/test_package.yaml
Report code coverage in CI: restores reporting coverage after dropping it in commit `035eebd` due to incompatibilities with the testing framework used at the time (`nose`). `nose` was replaced by `pytest` in commit e36ee38.
> ENH: Report code coverage in CI

- .github/workflows/doc_build.yaml
- doc/index.rst
- DOC: Remove unnecessary indentation in package TOC entry
- DOC: Miscellaneous style improvements to documentation index file
- ENH: Make the documentation build be permissive with warnings
> ENH: Make the documentation build be permissive with warnings

- .github/workflows/test_package.yaml
- pyproject.toml
Restrict dependencies versions for release.
Restrict the supported Python versions to those where the tool is known to be working (>=3.9, <3.12).
> ENH: Restrict dependencies versions for release

- doc/installation_instructions.rst
Update installation instructions:
- Update the dependencies versions.
- `Canopy` is no longer maintained/available, so remove it.
- Update the instal command to use `pip` as the build system has been changed and there is no `setup.py` file.
> DOC: Update installation instructions

- tract_querier/tract_math/operations.py
- tract_querier/tract_math/tensor_operations.py
Remove Python 2.x legacy conditional import statement: import `OrderedDict` from `collections`.
Support for Python 2.x was dropped following the discussion in https://github.com/demianw/tract_querier/pull/5.
> ENH: Remove Python 2.x legacy conditional import statement

- scripts/tract_querier
- tract_querier/tract_math/operations.py
- tract_querier/tract_math/tract_operations.py
Fixes issue #85
Changed:
get_data() --> get_fdata()
get_affine() --> affine
---
I have tested my update locally on a case and it looks identical to before-update.
> Fix Nibabel deprecation warnings

- scripts/tract_querier
- tract_querier/tract_math/operations.py
- tract_querier/tract_math/tract_operations.py
Fix `NiBabel` deprecation warnings:
- Call `get_fdata()` instead of `get_data()`: `get_data()` is deprecated since version 3.0 and raises an error since version 5.0.
- Call `affine` instead of `get_affine()`: `get_affine()` is deprecated since version 2.1 and raises an error since version 4.0.
The required minimum `NiBabel` version is 3.0 as of the current `HEAD`: commit 221b068.
Fixes:
```
tract_querier/scripts/query_tracts.py:138: DeprecationWarning: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).
* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
img = labels_nii.get_data()
```
and
``` …
```
> ENH: Fix `NiBabel` deprecation warnings

- scripts/tract_querier
Define script functions before `main`: although not mandated by PEP 8, defining script functions before the `main` method is common practice and allows to have a better understanding when reading the `main` method.
> STYLE: Define script functions before `main`

- scripts/tract_math
- scripts/tract_querier
Use a dedicated function to parse script input arguments: improves readaibility, and reduces the complexity of the `main` method.
> STYLE: Use a dedicated function to parse script input arguments

- scripts/tract_math
Miscellaneous import cleanup in `tract_math` script:
- Remove unused imports: do not import `os` and `warning`.
- Remove duplicate imports: remove duplicate `sys` import statement.
Take advantage of the commit to remove the commented statement appending the parent directory to the path.
> STYLE: Miscellaneous import cleanup in `tract_math` script

- tract_querier/query_processor.py
Prefer using `visit_Constant` instead of `visit_Num` and `visit_Str`: both were deprecated since Python 3.8.
Fixes:
```
tract_querier/tests/test_query_eval.py: 40 warnings
tract_querier/tests/test_query_files.py: 6527 warnings
/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/ast.py:407:
DeprecationWarning: visit_Num is deprecated; add visit_Constant
return visitor(node)
```
and
```
tract_querier/tests/test_query_eval.py: 1 warning
tract_querier/tests/test_query_files.py: 24 warnings
/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/ast.py:407:
DeprecationWarning: visit_Str is deprecated; add visit_Constant
return visitor(node)
```
raised for example in:
https://github.com/demianw/tract_querier/actions/runs/12187495803/job/33998410948?pr=61#step:6:75 and …
> ENH: Prefer using `visit_Constant`

- .github/workflows/doc_build.yaml
Specify 3.10 as the Python version in CI documentation build.
Fixes:
```
ERROR: Package 'tract-querier' requires a different Python: 3.12.3 not in '<3.12,>=3.9'
Error: Process completed with exit code 1.
```
raised for example in:
https://github.com/demianw/tract_querier/actions/runs/12833173197/job/35787564658?pr=78
> ENH: Specify Python version in CI documentation build

- pyproject.toml
- tract_querier/tractography/tests/test_tractography.py
- tract_querier/tractography/trackvis.py
Remove dependency on `nibabel.trackvis`: the module was deprecated in `NiBabel` 2.5.0 and removed in version 4.0.0. So this patch set adapts the `tractography.trackvis` code so that it uses the modern API.
Add a tolerance when comparing streamline data in `equal_tracts` to account for some precision loss since data is transformed to `float32` (vs `float64`) when applying the operations of the `NiBabel` API.
Fixes:
```
tract_querier/tractography/tests/test_tractography.py::test_saveload_trk
site-packages/nibabel/deprecated.py:35:
DeprecationWarning:
The trackvis interface has been deprecated and will be removed in v4.0; please use the 'nibabel.streamlines' interface.
mod = __import__(self._module_name, fromlist=[''])
```
and
```
tract_querier/tractography/trackvis.py:7: in <module>
from …
```
> ENH: Remove dependency on `nibabel.trackvis`

- tract_querier/query_processor.py
- ENH: Use `ast.Constant` instead of the deprecated `ast.Str`
- ENH: Use `ast` node value property instead of deprecated `n` or `s`
> ENH: Update deprecated `ast` items
